import type { TimelineEvent } from "@/types";

export const demoTimeline: TimelineEvent[] = [
  {
    id: "tl_blr_2026_03",
    projectId: "bhopal-lake-restoration",
    date: "2026-03-01",
    title: "Initial Site Condition",
    description: "Baseline documentation of four shoreline locations before any cleanup work began.",
    aiSummary:
      "Initial media shows visible accumulated waste along sections of the lake shoreline, on the Ghat 2 steps and around Inflow Channel 1.",
    phase: "before",
    mediaCount: 34,
    assetIds: ["asset_blr_before_01", "asset_blr_before_02", "asset_blr_before_03", "asset_blr_before_04"],
  },
  {
    id: "tl_blr_2026_04",
    projectId: "bhopal-lake-restoration",
    date: "2026-04-01",
    title: "Waste Removal Activities",
    description: "Shoreline cleanup crews, a community cleanup drive and a waste collection point.",
    aiSummary:
      "Media shows workers removing waste from the shoreline with rakes, filled collection sacks at a collection point, and floating debris being removed by boat.",
    phase: "during",
    mediaCount: 41,
    assetIds: ["asset_blr_during_01", "asset_blr_during_02", "asset_blr_during_03"],
  },
  {
    id: "tl_blr_2026_05",
    projectId: "bhopal-lake-restoration",
    date: "2026-05-01",
    title: "Restoration Activities",
    description: "Sapling plantation along the bank and clearing of the inflow channel.",
    aiSummary:
      "Media shows saplings with wooden tree guards planted along Sector D and workers clearing debris around Inflow Channel 1.",
    phase: "during",
    mediaCount: 27,
    assetIds: ["asset_blr_during_04", "asset_blr_during_05"],
  },
  {
    id: "tl_blr_2026_06",
    projectId: "bhopal-lake-restoration",
    date: "2026-06-01",
    title: "Post-Project Condition",
    description: "Repeat photography from the baseline viewpoints after work concluded.",
    aiSummary:
      "Post-project media from the same viewpoints shows little visible waste, more visible vegetation along the bank and a clearly visible water surface.",
    phase: "after",
    mediaCount: 26,
    assetIds: ["asset_blr_after_01", "asset_blr_after_02", "asset_blr_after_03", "asset_blr_after_04"],
  },
  {
    id: "tl_csi_2026_02",
    projectId: "community-solar-installation",
    date: "2026-02-01",
    title: "Site Readiness Survey",
    description: "Rooftop survey of participating households.",
    aiSummary: "Media shows tiled village rooftops without solar equipment.",
    phase: "before",
    mediaCount: 21,
    assetIds: ["asset_csi_before_01"],
  },
  {
    id: "tl_csi_2026_04",
    projectId: "community-solar-installation",
    date: "2026-04-01",
    title: "Panel Installation",
    description: "Mounting structures and panel installation.",
    aiSummary: "Media shows technicians working on rooftops with panels mounted on a neighbouring roof.",
    phase: "during",
    mediaCount: 33,
    assetIds: ["asset_csi_during_01"],
  },
  {
    id: "tl_csi_2026_06",
    projectId: "community-solar-installation",
    date: "2026-06-01",
    title: "Commissioned Systems",
    description: "Documentation of completed rooftop systems.",
    aiSummary: "Media shows solar arrays mounted on three rooftops.",
    phase: "after",
    mediaCount: 20,
    assetIds: ["asset_csi_after_01"],
  },
  {
    id: "tl_vwa_2026_01",
    projectId: "village-water-access",
    date: "2026-01-01",
    title: "Existing Water Point",
    description: "Documentation of the existing hand pump.",
    aiSummary: "Media shows a dry hand pump with water containers waiting beside it.",
    phase: "before",
    mediaCount: 14,
    assetIds: ["asset_vwa_before_01"],
  },
  {
    id: "tl_vwa_2026_04",
    projectId: "village-water-access",
    date: "2026-04-01",
    title: "Pipeline Construction",
    description: "Trenching and pipe laying through the main lane.",
    aiSummary: "Media shows workers laying pipe along a trench through the village.",
    phase: "during",
    mediaCount: 31,
    assetIds: ["asset_vwa_during_01"],
  },
  {
    id: "tl_vwa_2026_07",
    projectId: "village-water-access",
    date: "2026-07-01",
    title: "Tap Stand Handover",
    description: "Completed tap stands handed over to the community.",
    aiSummary: "Media shows a tap stand with running water in use by a resident.",
    phase: "after",
    mediaCount: 16,
    assetIds: ["asset_vwa_after_01"],
  },
];
