import type { DashboardStats, Project } from "@/types";

export const DEMO_ORG_ID = "org_narmada_impact_collective";
export const DEMO_ORG_NAME = "Narmada Impact Collective";
export const PRIMARY_DEMO_PROJECT_ID = "bhopal-lake-restoration";

export const demoDashboardStats: DashboardStats = {
  projects: 12,
  mediaAssets: 438,
  analyzedPercent: 87,
  reportsGenerated: 24,
};

type Seed = Omit<Project, "organizationId" | "createdAt">;

const seeds: Seed[] = [
  {
    id: PRIMARY_DEMO_PROJECT_ID,
    name: "Bhopal Lake Restoration",
    description:
      "A lake restoration and waste removal initiative focused on improving shoreline cleanliness and restoring the surrounding environment.",
    type: "Environmental Restoration",
    location: "Bhopal, Madhya Pradesh",
    startDate: "2026-03-01",
    endDate: "2026-06-30",
    status: "completed",
    coverAssetId: "asset_blr_after_03",
    coverUrl: "/demo/lake-after-03.jpg",
    focusActivity: "Waste Removal",
    stats: { mediaAssets: 128, analyzedPercent: 96, focusActivityAssets: 31, phases: 4, reports: 6 },
  },
  {
    id: "community-solar-installation",
    name: "Community Solar Installation",
    description:
      "Rooftop solar installation for households and a community centre, documenting site readiness, installation work and commissioned systems.",
    type: "Renewable Energy",
    location: "Sehore, Madhya Pradesh",
    startDate: "2026-02-01",
    endDate: "2026-07-31",
    status: "active",
    coverAssetId: "asset_csi_after_01",
    coverUrl: "/demo/solar-after-01.jpg",
    focusActivity: "Panel Installation",
    stats: { mediaAssets: 74, analyzedPercent: 84, focusActivityAssets: 22, phases: 3, reports: 4 },
  },
  {
    id: "village-water-access",
    name: "Village Water Access",
    description:
      "Piped drinking-water access for village households, covering pipeline trenching, tap stand construction and community handover.",
    type: "Water & Sanitation",
    location: "Raisen, Madhya Pradesh",
    startDate: "2026-01-15",
    endDate: "2026-08-15",
    status: "active",
    coverAssetId: "asset_vwa_after_01",
    coverUrl: "/demo/water-after-01.jpg",
    focusActivity: "Pipeline Construction",
    stats: { mediaAssets: 61, analyzedPercent: 79, focusActivityAssets: 18, phases: 3, reports: 3 },
  },
  {
    id: "urban-tree-plantation",
    name: "Urban Tree Plantation Drive",
    description: "Native sapling plantation along arterial roads with tree guards and survival monitoring.",
    type: "Urban Greening",
    location: "Indore, Madhya Pradesh",
    startDate: "2025-11-01",
    endDate: "2026-04-30",
    status: "completed",
    coverUrl: "",
    focusActivity: "Plantation",
    stats: { mediaAssets: 34, analyzedPercent: 91, focusActivityAssets: 19, phases: 3, reports: 3 },
  },
  {
    id: "waste-segregation-program",
    name: "Solid Waste Segregation Program",
    description: "Ward-level household segregation training and collection point setup.",
    type: "Waste Management",
    location: "Jabalpur, Madhya Pradesh",
    startDate: "2026-01-10",
    endDate: "2026-09-30",
    status: "active",
    coverUrl: "",
    focusActivity: "Waste Segregation",
    stats: { mediaAssets: 29, analyzedPercent: 86, focusActivityAssets: 12, phases: 3, reports: 2 },
  },
  {
    id: "watershed-check-dams",
    name: "Watershed Check Dams",
    description: "Construction of stone check dams across seasonal streams in upland villages.",
    type: "Water Conservation",
    location: "Dewas, Madhya Pradesh",
    startDate: "2025-12-01",
    endDate: "2026-05-31",
    status: "completed",
    coverUrl: "",
    focusActivity: "Construction",
    stats: { mediaAssets: 26, analyzedPercent: 92, focusActivityAssets: 14, phases: 3, reports: 2 },
  },
  {
    id: "school-sanitation-upgrade",
    name: "School Sanitation Upgrade",
    description: "Toilet block renovation and handwashing stations in government schools.",
    type: "Water & Sanitation",
    location: "Vidisha, Madhya Pradesh",
    startDate: "2026-04-01",
    endDate: "2026-10-31",
    status: "active",
    coverUrl: "",
    focusActivity: "Renovation",
    stats: { mediaAssets: 22, analyzedPercent: 77, focusActivityAssets: 9, phases: 3, reports: 1 },
  },
  {
    id: "community-kitchen-gardens",
    name: "Community Kitchen Gardens",
    description: "Kitchen garden kits and training for women's self-help groups.",
    type: "Food Security",
    location: "Narmadapuram, Madhya Pradesh",
    startDate: "2026-03-15",
    endDate: "2026-11-30",
    status: "active",
    coverUrl: "",
    focusActivity: "Cultivation",
    stats: { mediaAssets: 18, analyzedPercent: 83, focusActivityAssets: 7, phases: 2, reports: 1 },
  },
  {
    id: "clean-cookstove-distribution",
    name: "Clean Cookstove Distribution",
    description: "Distribution and usage follow-up of improved cookstoves in rural households.",
    type: "Clean Energy",
    location: "Sagar, Madhya Pradesh",
    startDate: "2026-02-15",
    endDate: "2026-06-15",
    status: "completed",
    coverUrl: "",
    focusActivity: "Distribution",
    stats: { mediaAssets: 17, analyzedPercent: 88, focusActivityAssets: 8, phases: 2, reports: 1 },
  },
  {
    id: "rainwater-harvesting",
    name: "Rainwater Harvesting Structures",
    description: "Rooftop rainwater harvesting for public buildings ahead of the monsoon.",
    type: "Water Conservation",
    location: "Ujjain, Madhya Pradesh",
    startDate: "2026-04-15",
    endDate: "2026-07-15",
    status: "active",
    coverUrl: "",
    focusActivity: "Construction",
    stats: { mediaAssets: 14, analyzedPercent: 71, focusActivityAssets: 6, phases: 2, reports: 1 },
  },
  {
    id: "pond-rejuvenation",
    name: "Village Pond Rejuvenation",
    description: "Desilting and embankment repair of a community pond.",
    type: "Environmental Restoration",
    location: "Guna, Madhya Pradesh",
    startDate: "2026-06-01",
    endDate: "2026-12-31",
    status: "planning",
    coverUrl: "",
    focusActivity: "Desilting",
    stats: { mediaAssets: 9, analyzedPercent: 67, focusActivityAssets: 3, phases: 1, reports: 0 },
  },
  {
    id: "plastic-free-markets",
    name: "Plastic-Free Market Initiative",
    description: "Cloth bag distribution and vendor engagement in weekly markets.",
    type: "Waste Management",
    location: "Gwalior, Madhya Pradesh",
    startDate: "2026-05-01",
    endDate: "2026-12-31",
    status: "planning",
    coverUrl: "",
    focusActivity: "Community Engagement",
    stats: { mediaAssets: 6, analyzedPercent: 50, focusActivityAssets: 2, phases: 1, reports: 0 },
  },
];

export const demoProjects: Project[] = seeds.map((p) => ({
  ...p,
  organizationId: DEMO_ORG_ID,
  createdAt: `${p.startDate}T09:00:00.000Z`,
}));

export const FEATURED_PROJECT_IDS = [
  PRIMARY_DEMO_PROJECT_ID,
  "community-solar-installation",
  "village-water-access",
];
