import { fail, handleError, ok, readJson, strField } from "@/lib/api";
import { generateProjectReport } from "@/services/reports";

/** Body: { projectId } -> Report (generated by the active AI provider and saved) */
export async function POST(req: Request) {
  const body = await readJson(req);
  const projectId = body ? strField(body, "projectId") : "";
  if (!projectId) return fail("projectId is required", 422, "validation_error");
  try {
    const report = await generateProjectReport(projectId);
    return report ? ok(report, { status: 201 }) : fail("Project not found", 404, "not_found");
  } catch (e) {
    return handleError(e, "Report generation failed");
  }
}
